### ISSUE TITLE
Review how to handle non-unique codes

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#47] opened 2019-08-12 15:21 UTC
NIEM includes several code sets that do not have unique code values, like Hazmat codes and county codes.  For example, there are currently 50 county "001" codes in NIEM, one for each state.  

Review if there are better options for representing these kinds of codes, like ...

- Use the NIEM Code Lists specification to represent these codes in a CSV format, along with additional columns.  For the county code example, adding the state code column would be useful.
-  Look for alternate code sets with unique values that might be a better fit for an XML schema representation.
- Use a hybrid approach - create unique enumerations for the schemas and instances.  Provide a link between the new enums and the original codes and definitions in a Code Lists CSV file.

NIEM code sets with duplicate codes:

- [fips:USCountyCodeNumericSimpleType](https://tools.niem.gov/niemtools/ssgt/SSGT-GetType.iepd?typeKey=o1-boi), including
  - 001 - Adair County
  - 001 - Adams County
  - 001 - Albany County
- [hazmat:HazmatUNCodeSimpleType](https://tools.niem.gov/niemtools/ssgt/SSGT-GetType.iepd?typeKey=o1-32j), including
  - NA1760 - Compounds, tree killing, liquid or Compounds, weed killing, liquid
  - NA1760 - Compounds, cleaning liquid
  - NA1760 - Chemical kit
  - NA1760 - Ferrous chloride, solution
- [dea:DrugCodeSimpleType](https://tools.niem.gov/niemtools/ssgt/SSGT-GetType.iepd?typeKey=o1-boe), including
  - 2100 - Talbutal
  - 2100 - Butalbital
  - 2100 - Butabarbital (secbutabarbital)
  - 2100 - Vinbarbital
- [ncic:VMOCodeSimpleType](https://tools.niem.gov/niemtools/ssgt/SSGT-GetType.iepd?typeKey=o1-9s), including
  - 100 - 100
  - 100 - 100 SERIES
  - 100 - 100 E SERIES
  - 100 - 1000
  - 100 - 1000 & 1000GL

**Comment by webb** [comment] 2020-02-18 15:25
Option 1: don't put multiple enumerations with the same code in the same simple type.
Option 2: support the poorly-normalized code lists with CSVs linked in via the code lists spec.
Option 3: Merge secondary code lists and primary code lists together (eg., replace separate vehicle model code with a merged vehicle make-model code)

**Comment by mikehulme** [comment] 2020-02-18 17:23
Consider that generally, it is by design these code lists do not have unique values. The applicable code (from the non-unique values) is determined by some context known to the information exchange participants. The code lists are being used successfully and have been for many years, not just for information exchange but in the participating information systems themselves. So I would recommend two considerations: (1) are there real-world cases where this is a problem, or is it really a theoretical/academic issue? (2) If a new solution is put it place, I would strongly recommend adding it as an alternative rather than replacing these existing, in some cases widely used code lists. Leaving the existing code list would obviate the need for code translations by information systems using the existing codes.

**Comment by cdmgtri** [comment] 2020-02-21 23:04
Closing issue.  Can reopen if someone reports issues with duplicate code values.

**Comment by cdmgtri** [comment] 2020-03-24 17:09
Reopened by request for further discussion.

**Comment by mikehulme** [comment] 2020-03-24 17:13
Who requested this be reopened and what is the basis for further discussion?

**Comment by cdmgtri** [comment] 2020-03-24 20:02
After further discussion, the Harmonization Workgroup decided that it is better to create an alternative that provides unique codes once in NIEM rather than having users create a variety of custom solutions.  

The original types and codes will remain as is.  Additional types will be created to provide unique codes for these kinds of hierarchical code sets.  Hyphens will likely be used as the delimiter.  

@cdmgtri will provide a specific proposal for further review.

**Comment by cdmgtri** [comment] 2020-04-02 22:19
Proposals:

### FIPS county codes

Create a new type fips:USStateCountyCodeType that combines the numeric state and county codes, with no delimiter.  Tableau uses format this to geocode counties and I suspect others may use that format as well.

Example:  

Code | Definition
--- | ---
13121 | Fulton County, Georgia

### DEA drug codes

The source we use for the DEA drug codes does not have any additional fields we can use to create unique codes:

http://www.deadiversion.usdoj.gov/schedules/orangebook/d_cs_drugcode.pdf

Example (see codes "2100"):

![drugCodes](https://user-images.githubusercontent.com/18708608/78302162-42da1c80-7508-11ea-999c-c2de91f45569.png)

Unless there are additional distinguishing fields, not much we can do for this one.

### Hazmat codes

Duplicate code values from NIEM's latest hazmat code update:

Code | Definition
--- | ---
UN1005 | Ammonia,   anhydrous
UN1005 | Ammonia,   anhydrous
UN3318 | Ammonia   solution, relative density less than 0.880 at 15   degrees C in water, with more than 50 percent ammonia
UN3318 | Ammonia   solution, relative density less than 0.880 at 15   degrees C in water, with more than 50 percent ammonia
UN1744 | Bromine
UN1744 | Bromine   solutions
UN1744 | Bromine   solutions
UN3316 | Chemical   kits
UN3316 | First   aid kits
UN3316 | First   aid kits
UN1230 | Methanol
UN1230 | Methanol

Could leave as is or could drop duplicate codes with duplicate definitions.  This would still leave a few duplicate codes with different definitions:

Code | Definition
--- | ---
UN1005 | Ammonia,   anhydrous
UN3318 | Ammonia   solution, relative density less than 0.880 at 15   degrees C in water, with more than 50 percent ammonia
UN1744 | Bromine
UN1744 | Bromine   solutions
UN3316 | Chemical   kits
UN3316 | First   aid kits
UN1230 | Methanol

### FBI VMA codes

The FBI is reviewing this and is considering a new combined code set for beta.  

This could look something like:

Code | Definition
--- | ---
HOND-ACC | HONDA ACCORD
HOND-CIV | HONDA CIVIC
TOYT-CAM | TOYOTA CAMRY

**Comment by mikehulme** [comment] 2020-04-03 03:48
###  FIPS county codes
This works and is acceptable since the state codes are always exactly two digits and the county codes are always exactly three digits, using leading zeros. e.g.:

| Code   | Definition              |
|:------ |:----------------------- |
| 01001  | Autauga County, Alabama |

### DEA drug codes
Could we have something like a single entry for each code, with the definition comprising the concatenation of all the SUBSTANCE values delimited by semicolons, and the OTHER NAMES delimited by the word "including" followed by a comma? For example:

| Code  | Definition                                                                  |
|:----  |:----------------------------------------------------------------------------|
| 2100  | Aprobarbital, including Alurate; Barbituric acid deriverative, including barbiturates not specifically listed; Butabarbital (secbutabarbital), including Butisol, Butibel; Butalbital, including Florinal, Butalbital with aspirin; Butobarbital (butethal), including Soneryl (UK); Talbutal, including Lotusate; Thiamylal, including Surital; Thiopental, including Pentothol; Vinbarbital, including Devinal, vinbarbitone |

The description can be long, but it maintains all possible descriptions and solves the problem of multiple occurrences of the same code value.

### HAZMAT Codes
Could we have a single entry for each code, with the definition comprising the concatenation of all the definition values delimited by commas? For example:

| Code    | Definition                    |
|:------  |:------------------------------|
| UN7144  | Bromine, bromine solutions    |
| UN3316  | Chemical kits, first aid kits |

### FBI VMA-VMO codes
The solution being contemplated by FBI CJIS looks good to me.

**Comment by bdhandspicker** [comment] 2020-04-03 17:46
The "DEA Number" issue is a red herring. I believe it is usually referred to as "NDCproduct code" and it is not intended to represent an individual pharmaceutical product, but rather the primary drug (chemical) in the product. E.g. 2100 is the code for a specific barbituate formula and you can think of the 9 medications listed in the example drug schedule as barbituate products with the 2100 formula. So that "DEA Number" is more like a category. To uniquely represent individual products the DEA uses a structure  comprised of the  NDCproduct code and SPL documentID. For more info check out https://www.fda.gov/drugs/drug-approvals-and-databases/ndc-product-file-definitions. [And, BTW, I am not an expert at this so if anyone else is an expert, please weigh in and correct me.]

**Comment by DonClysdale** [comment] 2020-04-07 17:29
We also need to discuss/define the order/structure of combined codes. I believe it makes sense to always have the broader entity code first (to accommodate sorting), separated by a hyphen from the more specific entity - like parent-child similar what was done with ISO 3166 country codes and ISO 3166 country subdivision codes and the vehicle codes above.

**Comment by cdmgtri** [comment] 2020-08-04 19:55
### Status

(1)  The FBI has updated their vehicle model codes to a unique code set, linking each model with its make.

Examples:

Code | Definition
--- | ---
AUDI-200 | AUDI - 200LS
AUDI-850 | AUDI - 850
BMW-200 | BMW - 2000 SERIES
BMW-850 | BMW - 850I
HOND-ACC | HONDA MOTOR CO., LTD   - ACCORD, ACCORD CROSSTOUR
HOND-CIV | HONDA MOTOR CO., LTD   - CIVIC (AND CRX), CIVIC DEL SOL
TOYT-CAM | TOYOTA - CAMRY
TOYT-COA | TOYOTA - COROLLA,   COROLLA IM

(2)  The Harmonization workgroup recommends adding a new FIPS county code set pairing 2-digit state codes wither 3-digit county codes in order to create a unique set of county codes.  This 5-digit format with no delimiter seems to already be used in various places outside of NIEM, making this format the best choice for interoperability.

(3)  The Harmonization workgroup recommends leaving Hazmat codes and DEA drug codes as is, only removing identical code + definition duplicates when they occur.  Different definitions for a single code value will still be maintained.

(4)  The Harmonization workgroup recommends leaving the DEA drug code name as is for now.  The name is taken from the code table source.  The NDC product code has different code values and comes from a different authoritative source (the FDA) than the DEA drug codes.  NIEM may represent the NDC data at some point in the future though with content in a Health domain.

**Closed** 2020-08-26 22:33 UTC
Labels: 5.0, codes
